# Generated by Django 6.0.3 on 2026-08-04 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_persistent_thread_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cube_query', models.JSONField(default=dict, help_text='{"measures": [...], "dimensions": [...], "timeDimensions": [...], "filters": [...], "limit": 500}')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive metrics are hidden from the agent without deleting the row.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_definitions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Metric Definition',
                'verbose_name_plural': 'Metric Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PendingCubeMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_name', models.CharField(help_text='Must match an existing model/cubes/<cube_name>.yml.', max_length=100)),
                ('measure_name', models.CharField(help_text='snake_case Cube measure name.', max_length=100)),
                ('measure_type', models.CharField(choices=[('count', 'count'), ('sum', 'sum'), ('avg', 'avg'), ('min', 'min'), ('max', 'max'), ('countDistinct', 'countDistinct'), ('number', 'number')], max_length=20)),
                ('sql_expression', models.CharField(blank=True, help_text='Cube sql: value, e.g. {CUBE}."SOME_COLUMN". Not required for type=count.', max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('written', 'Written to cube schema'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_cube_measures_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_cube_measures_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Cube Measure',
                'verbose_name_plural': 'Pending Cube Measures',
                'ordering': ['-requested_at'],
            },
        ),
    ]
