# Generated by Django 6.0.3 on 2026-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_import_metrics_yaml'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcubemeasure',
            name='action',
            field=models.CharField(choices=[('add', 'Add new measure'), ('edit', 'Edit existing measure')], default='add', help_text='"add" splices a new measure in; "edit" replaces an existing one by name.', max_length=10),
        ),
    ]
