# Generated by Django 6.0.3 on 2026-04-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='streamlit_url',
            field=models.URLField(default='https://example.com'),
            preserve_default=False,
        ),
    ]
