# Generated by Django 6.0.3 on 2026-04-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_dashboard_streamlit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='facility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
