# Generated by Django 6.0.3 on 2026-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_dashboard_facility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='facility',
            new_name='client',
        ),
    ]
