# Generated by Django 6.0.3 on 2026-04-27 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_rename_facility_dashboard_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dashboard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
