# Generated by Django 6.0.3 on 2026-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0006_rebuild_dashboard_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='analytics_a_client__9cc270_idx',
            old_name='dashboard_client_active_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboard',
            new_name='analytics_a_slug_6224ba_idx',
            old_name='dashboard_slug_idx',
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
