# Generated by Django 6.0.3 on 2026-07-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0007_rename_dashboard_client_active_idx_analytics_a_client__9cc270_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='redash_api_key',
            field=models.CharField(blank=True, help_text='Per-query API key from Redash (Query -> More Options -> API Key). Scopes what this specific embed can see.', max_length=100),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='redash_query_id',
            field=models.PositiveIntegerField(blank=True, help_text='Redash query ID powering this dashboard (used instead of streamlit_url).', null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='redash_visualization_id',
            field=models.PositiveIntegerField(blank=True, help_text='Redash visualization ID to embed (Query -> visualization -> Embed).', null=True),
        ),
    ]
