# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0008_dashboard_redash_api_key_dashboard_redash_query_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='redash_dashboard_url',
            field=models.URLField(blank=True, help_text='Full Redash dashboard URL to embed (Dashboard -> Share -> Publish, e.g. ".../public/dashboards/<token>?org_slug=default"). Used instead of redash_query_id/redash_visualization_id when embedding a whole Redash dashboard rather than a single chart.'),
        ),
    ]
