# Generated by Django 6.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics_app', '0009_dashboard_redash_dashboard_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sql_text', models.TextField()),
                ('redash_query_id', models.PositiveIntegerField(unique=True)),
                ('redash_data_source_id', models.PositiveIntegerField()),
                ('redash_data_source_name', models.CharField(blank=True, max_length=200)),
                ('source_table', models.CharField(blank=True, help_text='HOSPITALS.REPORTING.<table> this was auto-generated from, blank for custom queries.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reporting queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
