# Generated by Django 6.0.3

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('analytics_app', '0010_reportingquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingquery',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility this query is scoped to (via a source_schema filter), blank for custom queries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporting_queries', to='core.facility'),
        ),
    ]
