services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: "true"
    entrypoint: ["/bin/bash", "+x", "/entrypoint.sh"]
    networks:
      - dashboard-net

  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - /opt/postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - dashboard-net

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - dashboard-net

volumes:
  web-django:
  web-static:
  redisdata:

networks:
  dashboard-net:
    name: dashboard-net
