version: "3"

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: "true"
    entrypoint: ["/bin/bash", "+x", "/entrypoint.sh"]
  
  streamlit:
    restart: always
    build: .
    container_name: streamlit-container
    expose:
      - "8501"
    ports:
      - "8501:8501"
    volumes:
      - ./:/usr/src/app
    env_file: .env
    working_dir: /usr/src/app
    depends_on:
      - postgres
      - redis
    command: >
      streamlit run analytics_app/dashboards/dynamic_file_loader.py
      --server.port=8501
      --server.address=0.0.0.0
      --server.headless=true
      --server.enableCORS=false
      --server.enableXsrfProtection=false
      
  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - /opt/postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  

volumes:
  web-django:
  web-static:
  redisdata: