# Generated by Django 6.0.3 on 2026-05-25 08:57
# This migration kept as a no-op to satisfy dependency references from other apps.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # All operations folded into 0001_initial during consolidation.
        # This migration kept as an empty placeholder to preserve the
        # dependency reference from authentication.0002.
    ]
