# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_client_logo_alter_systemsettings_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='reporting_source_schema',
            field=models.CharField(blank=True, help_text='The exact value this facility\'s rows use in the HOSPITALS.REPORTING "source_schema" column (e.g. "Kisumu") — not necessarily related to the facility name above. Used to scope synced Redash reporting queries to this facility.', max_length=100),
        ),
    ]
