# Generated by Django 6.0.3 on 2026-08-27 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ticket_ticketcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_status_0cf843_idx',
            old_name='core_ticket_status_2a1b4a_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='core_ticket_created_3cb060_idx',
            old_name='core_ticket_created_9c2e8f_idx',
        ),
    ]
