# Generated by Django 6.0.3 on 2026-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_analyst_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='workbook',
            name='google_sheet_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='workbook',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Uploaded file'), ('google_sheet', 'Linked Google Sheet')], default='upload', max_length=16),
        ),
    ]
