# Generated by Django 6.0.3 on 2026-07-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='self_servic_session_4c903f_idx',
            old_name='self_servic_session_created_idx',
        ),
        migrations.RenameIndex(
            model_name='chatsession',
            new_name='self_servic_user_id_5f462c_idx',
            old_name='self_servic_user_id_started_idx',
        ),
    ]
