# Generated by Django 6.0.3 on 2026-08-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0002_rename_self_servic_session_created_idx_self_servic_session_4c903f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
