# Generated by Django 6.0.3 on 2026-08-27 08:26

import self_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0003_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chart_caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='chart_image',
            field=models.FileField(blank=True, null=True, upload_to=self_service.models.chart_image_upload_path),
        ),
    ]
