# Generated by Django 6.0.3 on 2026-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_service', '0004_chatmessage_chart_caption_chatmessage_chart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='thread_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
