# Generated by Django 6.0.3 on 2026-04-27 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



def create_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    roles = [
        "Client Admin",
        "Facilities Admin",
        "Facility Admin",
    ]

    for role in roles:
        Group.objects.get_or_create(name=role)

def remove_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=[
        "Client Admin",
        "Facilities Admin",
        "Facility Admin",
    ]).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, help_text='Primary contact number, including country code.', max_length=32)),
                ('client', models.CharField(blank=True, help_text='Client / organization the user belongs to.', max_length=120)),
                ('facility', models.CharField(blank=True, help_text='Facility the user is primarily assigned to. Leave blank for Facilities Admin / Client Admin.', max_length=120)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.RunPython(create_roles, remove_roles),
    ]
