# Generated by Django 6.0.3 on 2026-05-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0002_alter_client_logo_alter_systemsettings_is_public_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Client Admin', 'Client Admin'), ('Facilities Admin', 'Facilities Admin'), ('Facility Admin', 'Facility Admin')], db_index=True, default='Facility Admin', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client / organisation the user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.client'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='facility',
            field=models.ForeignKey(blank=True, help_text='Facility the user is primarily assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.facility'),
        ),
    ]
